function [cfg,ext] = round1_local_extension_config()
% Configuration for s021+ extensions based exclusively on Round-1 WM95.
cfg=load_project_config();
ext=struct();
ext.root=cfg.output_dir;
ext.jhu_file=fullfile(cfg.data_dir,'JHU','JHU-ICBM-labels-2mm.nii.gz');
ext.jhu_xml=fullfile(cfg.data_dir,'JHU','JHU-ICBM-labels-2mm.xml');
ext.n_signflip=5000;
ext.cluster_forming_p=0.001;
ext.gradient_projection_lambda=1;
ext.behavior_n_permutations=1000;
ext.behavior_outer_folds=5;
ext.behavior_outer_repeats=20;
ext.behavior_inner_folds=5;
ext.behavior_lambda_grid=logspace(-4,4,25);
ext.behavior_outcomes={'CogTotalComp_AgeAdj','CogFluidComp_AgeAdj', ...
    'CogCrystalComp_AgeAdj','PMAT24_A_CR'};
ext.confound_distance_bins_mm=[0 2 4 6 8 10 15 20 30 45 inf];
ext.spatial_null_n_permutations=5000;
ext.spatial_null_block_mm=12;
ext.g1_bin_count=10;
ext.symmetry_pair_tolerance_mm=2.5;
names={ ...
 'local_r2_fc', ...
 'local_r2_fc_inference', ...
 'beta_fc_gradient_templates', ...
 'beta_fc_gradient_subject_inference', ...
 'jhu_localization', ...
 'behavior_local_prediction', ...
 'local_extension_summary', ...
 'session_local_r2_fc_validation', ...
 'cross_session_gradient_validation', ...
 'local_validation_summary', ...
 'spatial_confound_maps', ...
 'spatial_confound_control', ...
 'spatial_autocorr_null', ...
 'g1_binned_cortical_contribution', ...
 'hemispheric_symmetry', ...
 'local_story_summary'};
ext.result_dirs=cell(numel(names),1);
for i=1:numel(names)
    ext.result_dirs{i}=fullfile(ext.root,sprintf( ...
        'result_s%03d_%s',20+i,names{i}));
    ensure_dir(ext.result_dirs{i});
end
end
