%% s021_compute_local_r2_fc
% Within-subject WM normalization of R2 and FC strength. R2 residual maps
% quantify local prediction beyond each subject's local marginal FC strength.
clear; clc; [cfg,ext]=round1_local_extension_config();
wm=niftiread(cfg.wm_mask_final)>0; wm_idx=find(wm);
n=numel(cfg.subject_list); V=numel(wm_idx);
zR2=zeros(n,V,'single'); zFC_rms=zeros(n,V,'single');
zFC_meanabs=zeros(n,V,'single'); zFC_top10=zeros(n,V,'single');
R2_residual=zeros(n,V,'single'); spatial_r=zeros(n,1);

for s=1:n
    sid=cfg.subject_list{s};
    R=load(fullfile(cfg.result_dirs{5},sprintf( ...
        'sub-%s_ridge_main_results.mat',sid)), ...
        'R2_cv_voxel','wm_voxel_indices');
    F=load(fullfile(cfg.result_dirs{12},sprintf( ...
        'sub-%s_FC_profile.mat',sid)),'FC_profile','wm_voxel_indices');
    if ~isequal(R.wm_voxel_indices,wm_idx) || ...
            ~isequal(F.wm_voxel_indices,wm_idx)
        error('WM index mismatch for %s.',sid);
    end
    r2=double(R.R2_cv_voxel(:));
    fc=double(F.FC_profile);
    meanabs=mean(abs(fc),2);
    rmsfc=sqrt(mean(fc.^2,2));
    top10=mean(maxk(abs(fc),max(1,round(.10*size(fc,2))),2),2);
    zr=zscore(r2); zf=zscore(rmsfc);
    X=[ones(V,1),zf]; residual=zr-X*(X\zr);
    zR2(s,:)=single(zr); zFC_rms(s,:)=single(zf);
    zFC_meanabs(s,:)=single(zscore(meanabs));
    zFC_top10(s,:)=single(zscore(top10));
    R2_residual(s,:)=single(residual);
    spatial_r(s)=corr(zr,zf);
    save(fullfile(ext.result_dirs{1},sprintf( ...
        'sub-%s_local_r2_fc.mat',sid)),'sid','zr','zf','residual', ...
        'meanabs','rmsfc','top10','-v7.3');
end

group_mean_zR2=mean(zR2,1)';
group_mean_zFC_rms=mean(zFC_rms,1)';
group_mean_residual=mean(R2_residual,1)';
group_residual_consistency=mean(R2_residual>0,1)';
write_map_like(group_mean_zR2,wm_idx,cfg.wm_mask_final, ...
    fullfile(ext.result_dirs{1},'group_mean_local_zR2.nii.gz'));
write_map_like(group_mean_zFC_rms,wm_idx,cfg.wm_mask_final, ...
    fullfile(ext.result_dirs{1},'group_mean_local_zFC_RMS.nii.gz'));
write_map_like(group_mean_residual,wm_idx,cfg.wm_mask_final, ...
    fullfile(ext.result_dirs{1}, ...
    'group_mean_zR2_residualized_local_zFC.nii.gz'));
write_map_like(group_residual_consistency,wm_idx,cfg.wm_mask_final, ...
    fullfile(ext.result_dirs{1}, ...
    'group_local_R2_residual_positive_consistency.nii.gz'));
subject_id=string(cfg.subject_list(:));
subject_summary=table(subject_id,spatial_r, ...
    mean(zR2,2),mean(zFC_rms,2),std(R2_residual,0,2), ...
    'VariableNames',{'subject_id','spatial_r_zR2_zFC', ...
    'mean_zR2','mean_zFC','residual_spatial_sd'});
writetable(subject_summary,fullfile(ext.result_dirs{1}, ...
    'local_r2_fc_subject_summary.csv'));
save(fullfile(ext.result_dirs{1},'local_r2_fc_group_data.mat'), ...
    'zR2','zFC_rms','zFC_meanabs','zFC_top10','R2_residual', ...
    'group_mean_zR2','group_mean_zFC_rms','group_mean_residual', ...
    'group_residual_consistency','spatial_r','wm_idx','-v7.3');
fprintf('s021 complete: mean within-subject spatial r(zR2,zFC)=%.3f\n', ...
    mean(spatial_r));
