%% s025_localize_local_metrics_jhu
% Direct JHU overlap is primary; label-specific <=4 mm proximity is sensitivity.
clear; clc; [cfg,ext]=round1_local_extension_config();
wm=niftiread(cfg.wm_mask_final)>0; wm_idx=find(wm);
jhu=double(niftiread(ext.jhu_file)); labels=read_jhu_label_names(ext.jhu_xml);
L=load(fullfile(ext.result_dirs{1},'local_r2_fc_group_data.mat'), ...
    'group_mean_zR2','group_mean_zFC_rms','group_mean_residual', ...
    'group_residual_consistency');
G=load(fullfile(ext.result_dirs{4},'gradient_subject_inference.mat'), ...
    'mean_difference','q','p_fwer');
I=load(fullfile(ext.result_dirs{2},'local_r2_fc_inference.mat'), ...
    'p_fwer');
pix=mean(niftiinfo(ext.jhu_file).PixelDimensions(1:3));
rows=cell(height(labels),20);
for k=1:height(labels)
    id=labels.label_id(k); lm=jhu==id;
    direct=lm(wm_idx);
    dist=bwdist(lm)*pix; near4=dist(wm_idx)<=4;
    rows(k,:)={id,labels.label_name(k),nnz(lm),nnz(direct),nnz(near4), ...
        min(dist(wm)), ...
        mean(L.group_mean_zR2(direct),'omitnan'), ...
        mean(L.group_mean_zFC_rms(direct),'omitnan'), ...
        mean(L.group_mean_residual(direct),'omitnan'), ...
        mean(L.group_residual_consistency(direct),'omitnan'), ...
        mean(G.mean_difference(direct),'omitnan'), ...
        mean(I.p_fwer(direct)<.05,'omitnan'), ...
        mean(G.q(direct)<.05,'omitnan'), ...
        mean(G.p_fwer(direct)<.05,'omitnan'), ...
        mean(L.group_mean_zR2(near4),'omitnan'), ...
        mean(L.group_mean_zFC_rms(near4),'omitnan'), ...
        mean(L.group_mean_residual(near4),'omitnan'), ...
        mean(G.mean_difference(near4),'omitnan'), ...
        mean(I.p_fwer(near4)<.05,'omitnan'), ...
        mean(G.p_fwer(near4)<.05,'omitnan')};
end
T=cell2table(rows,'VariableNames',{ ...
    'label_id','label_name','atlas_voxels','direct_WM_voxels', ...
    'within4mm_WM_voxels','minimum_WM_distance_mm', ...
    'direct_mean_zR2','direct_mean_zFC','direct_mean_R2_residual', ...
    'direct_R2_residual_positive_consistency', ...
    'direct_mean_beta_minus_FC_G1', ...
    'direct_fraction_R2_residual_maxT_significant', ...
    'direct_fraction_G1_FDR_significant', ...
    'direct_fraction_G1_maxT_significant', ...
    'within4mm_mean_zR2','within4mm_mean_zFC', ...
    'within4mm_mean_R2_residual','within4mm_mean_beta_minus_FC_G1', ...
    'within4mm_fraction_R2_residual_maxT_significant', ...
    'within4mm_fraction_G1_maxT_significant'});
writetable(T,fullfile(ext.result_dirs{5},'JHU_local_metric_summary.csv'));
save(fullfile(ext.result_dirs{5},'JHU_local_metric_summary.mat'),'T','-v7.3');
fprintf('s025 complete: %d JHU labels summarized.\n',height(T));
