%% s027_summarize_local_extension
clear; clc; [cfg,ext]=round1_local_extension_config();
S=readtable(fullfile(ext.result_dirs{1},'local_r2_fc_subject_summary.csv'));
J=readtable(fullfile(ext.result_dirs{5},'JHU_local_metric_summary.csv'), ...
    'TextType','string');
B=readtable(fullfile(ext.result_dirs{6}, ...
    'behavior_local_prediction_summary.csv'),'TextType','string');
G=readtable(fullfile(ext.result_dirs{3},'gradient_template_summary.csv'), ...
    'TextType','string');
C=readtable(fullfile(ext.result_dirs{2},'local_R2_residual_clusters.csv'));
L=load(fullfile(ext.result_dirs{1},'local_r2_fc_group_data.mat'), ...
    'group_mean_residual');
GI=load(fullfile(ext.result_dirs{4},'gradient_subject_inference.mat'), ...
    'mean_difference','p_fwer');
RI=load(fullfile(ext.result_dirs{2},'local_r2_fc_inference.mat'),'p_fwer');
map_r=corr(double(L.group_mean_residual),double(GI.mean_difference));
joint=(RI.p_fwer(:)<.05) & (GI.p_fwer(:)<.05);
joint_voxels=nnz(joint);
if joint_voxels>0
    joint_sign_agreement=mean(sign(L.group_mean_residual(joint))== ...
        sign(GI.mean_difference(joint)));
else
    joint_sign_agreement=NaN;
end

metric=["mean_subject_spatial_r_zR2_zFC"; ...
    "median_subject_spatial_r_zR2_zFC"; ...
    "significant_R2_residual_clusters"; ...
    "beta_FC_G1_template_r"; ...
    "R2_residual_beta_minus_FC_G1_spatial_r"; ...
    "joint_maxT_significant_voxels"; ...
    "joint_sign_agreement"; ...
    "minimum_behavior_q_delta_r"; ...
    "minimum_behavior_q_delta_R2"];
value=[mean(S.spatial_r_zR2_zFC);median(S.spatial_r_zR2_zFC); ...
    sum(C.permutation_p<.05); ...
    G.value(G.metric=="beta_FC_template_r"); ...
    map_r;joint_voxels;joint_sign_agreement; ...
    min(B.permutation_q_delta_r);min(B.permutation_q_delta_R2)];
writetable(table(metric,value),fullfile(ext.result_dirs{7}, ...
    'local_extension_summary.csv'));

fig=figure('Color','w','Visible','off','Position',[50 50 1400 800]);
tiledlayout(2,2,'TileSpacing','compact','Padding','compact');
nexttile; histogram(S.spatial_r_zR2_zFC,20);
xlabel('Within-subject spatial r(zR2,zFC)');ylabel('Subjects');
title('Local prediction versus local FC');
nexttile;
valid=J.direct_WM_voxels>=20;
[~,ord]=sort(J.direct_mean_R2_residual(valid),'descend');
JJ=J(valid,:); JJ=JJ(ord,:); nshow=min(15,height(JJ));
barh(categorical(JJ.label_name(1:nshow)), ...
    JJ.direct_mean_R2_residual(1:nshow));set(gca,'YDir','reverse');
xlabel('Mean local R2 residual');title('Top direct-overlap JHU tracts');
nexttile;
scatter(L.group_mean_residual,GI.mean_difference,4,'filled', ...
    'MarkerFaceAlpha',.15);
xlabel('Mean local R2 residual');ylabel('Mean beta minus FC G1');
title(sprintf('Shared spatial organization, r=%.3f',map_r));
nexttile;
bar([min(B.permutation_q_delta_r),min(B.permutation_q_delta_R2)]);
xticklabels({'delta r','delta R2'});ylim([0 1]);ylabel('Minimum corrected q');
title('Behavior prediction: null result');
exportgraphics(fig,fullfile(ext.result_dirs{7}, ...
    'local_extension_summary.png'),'Resolution',200);
close(fig);
copyfile(fullfile(ext.result_dirs{5},'JHU_local_metric_summary.csv'), ...
    fullfile(ext.result_dirs{7},'JHU_local_metric_summary.csv'));
fprintf('s027 complete: summary saved to %s\n',ext.result_dirs{7});
