%% s030_summarize_local_validations
clear; clc; [cfg,ext]=round1_local_extension_config();
R=readtable(fullfile(ext.result_dirs{8}, ...
    'session_local_R2_residual_group_summary.csv'), ...
    'Delimiter',',','TextType','string','VariableNamingRule','preserve');
G=readtable(fullfile(ext.result_dirs{9}, ...
    'cross_session_gradient_group_summary.csv'), ...
    'Delimiter',',','TextType','string','VariableNamingRule','preserve');
S=readtable(fullfile(ext.result_dirs{7}, ...
    'local_extension_summary.csv'), ...
    'Delimiter',',','TextType','string','VariableNamingRule','preserve');
Sm=string(S{:,1}); Sv=double(S{:,2});
Rm=string(R{:,1}); Rv=double(R{:,2});
Gm=string(G{:,1}); Gv=double(G{:,2});
metric=[Sm;Rm;Gm];
value=[Sv;Rv;Gv];
writetable(table(metric,value),fullfile(ext.result_dirs{10}, ...
    'local_validation_summary.csv'));

% Direct JHU overlap for the independently validated maps.
RV=load(fullfile(ext.result_dirs{8}, ...
    'session_local_R2_fc_validation.mat'),'mean_residual','conjunction','wm_idx');
GV=load(fullfile(ext.result_dirs{9}, ...
    'cross_session_gradient_validation.mat'),'crossfit_mean','p_fwer');
jhu=double(niftiread(ext.jhu_file));
labels=read_jhu_label_names(ext.jhu_xml);
rows=cell(height(labels),7);
mean_r2=mean(RV.mean_residual,2);
for k=1:height(labels)
    direct=(jhu==labels.label_id(k)); direct=direct(RV.wm_idx);
    rows(k,:)={labels.label_id(k),labels.label_name(k),nnz(direct), ...
        mean(mean_r2(direct),'omitnan'), ...
        mean(RV.conjunction(direct),'omitnan'), ...
        mean(GV.crossfit_mean(direct),'omitnan'), ...
        mean(GV.p_fwer(direct)<.05,'omitnan')};
end
J=cell2table(rows,'VariableNames',{'label_id','label_name', ...
    'direct_WM_voxels','mean_cross_session_R2_residual', ...
    'fraction_R2_session_conjunction', ...
    'mean_cross_session_beta_minus_FC_G1', ...
    'fraction_G1_cross_session_maxT_significant'});
writetable(J,fullfile(ext.result_dirs{10}, ...
    'JHU_cross_session_validation_summary.csv'));

fig=figure('Color','w','Visible','off','Position',[50 50 1100 420]);
tiledlayout(1,2,'TileSpacing','compact','Padding','compact');
nexttile;
bar([Rv(Rm=="mean_subject_session_r"), ...
    Rv(Rm=="group_mean_map_r")]);
xticklabels({'Mean subject','Group map'});ylim([-1 1]);ylabel('Correlation');
title('Local R2 residual: REST1 versus REST2');grid on;
nexttile;
bar([Gv(Gm=="mean_subject_cross_direction_r"), ...
    Gv(Gm=="group_cross_direction_map_r")]);
xticklabels({'Mean subject','Group map'});ylim([-1 1]);ylabel('Correlation');
title('Beta-FC G1: cross-session projection');grid on;
exportgraphics(fig,fullfile(ext.result_dirs{10}, ...
    'local_validation_summary.png'),'Resolution',200);
close(fig);
fprintf('s030 complete: validation summary saved to %s\n',ext.result_dirs{10});
